### ISSUE TITLE
Binder taking too long to build

### ISSUE THREAD

**Issue by cesar-rocha** [NASA-SMODE/Maps#1]
Binder is taking too long to build, likely due to installation of cartopy and its dependencies. Can we speed this up?

**Comment by biavillasboas** [comment]
@cesar-rocha,  should we close this since #3 seems to also fix this issue? It builds pretty fast for me, have you tried it after we switched to Pangeo? My guess is that when we build using Pangeo's BinderHub, the default environment already comes with the Pangeo stack, so there are a lot fewer dependencies that need to be installed from environmentt.yml?

**Comment by cesar-rocha** [comment]
Yes, I tried when I reviewed your PR and it built it built in a couple of seconds!
